Lesson2
SkiNy66/blog pull request #2
Opened 2017-06-07 11:06 UTC by SkiNy66

2017-06-07 21:40 UTC, index01d requested changes
Есть небольшие замечания

2017-06-07 21:40 UTC, index01d commented on components/ui/BlogItem.jsx
> +const BlogItem = ({image, text, author, created_at, updated_at}) => (
лучше по всему проекту следовать единым правилам именования, в данном случае стоит исправить createdAt, updatedAt (camelCase)

2017-06-07 21:40 UTC, index01d commented on components/ui/BlogItem.jsx
> +      <TextBox>Создано: {moment(created_at).format('L')}</TextBox>
можно вынести функцию форматирования, чтобы можно было в любой момент заменить moment на что-то еще

2017-06-07 21:40 UTC, index01d commented on components/ui/BlogList.jsx
> +  image: React.PropTypes.shape({
можно реиспользовать propTypes от Image: `image: React.PropTypes.shape(Image.propTypes)`

2017-06-07 21:40 UTC, index01d commented on components/ui/BlogList.jsx
> +//      <BlogItem key={element.id} {...element} />
было то явно лучше, не стоит перемешивать js с nonjsx

2017-06-08 06:11 UTC, blackleadsu approved these changes

2017-06-08 07:06 UTC, merged