Lesson4
SkiNy66/blog pull request #4
Opened 2017-07-07 19:40 UTC by SkiNy66

2017-07-08 05:08 UTC, index01d requested changes
Запуск `./node_modules/eslint/bin/eslint.js --ext js,jsx ./src/` имеет к тебе ряд претензий, нужно бы поправить

2017-07-08 05:08 UTC, index01d commented on index.html
> +  <script src="assets/bundle.js"></script>
лучше подключить как `/assets/bundle.js`, чтобы не было проблем с подключением на страницах с URL-адресом отличным от корневого

2017-07-08 05:08 UTC, index01d commented on src/components/widgets/blog/Item.js
> +    <div style={{ float: 'left' }}>
должно быть в стилевом файле и импортиться выше

2017-07-08 05:08 UTC, index01d commented on src/components/widgets/blog/Item.js
> +    <div style={{ float: 'right' }}>
должно быть в стилевом файле (css) и импортиться выше

2017-07-08 08:47 UTC, SkiNy66 commented on src/components/widgets/blog/Item.js
> +    <div style={{ float: 'right' }}>
поправил все

2017-07-09 14:23 UTC, blackleadsu approved these changes

2017-07-09 16:39 UTC, merged